from pathlib import Path

file_types = {
    'zip': 'archive',
    'rar': 'archive',
    'pdf': 'pdf',
    'txt': 'text',
    'dwg': 'image',
    'xcf': 'image',
    'jpg': 'image',
    'jpx': 'image',
    'png': 'image',
    'gif': 'image',
    'webp': 'image',
    'cr2': 'image',
    'tif': 'image',
    'bmp': 'image',
    'jxr': 'image',
    'psd': 'image',
    'ico': 'image',
    'heic': 'image',
    '3gp': 'video',
    'mp4': 'video',
    'm4v': 'video',
    'mkv': 'video',
    'webm': 'video',
    'mov': 'video',
    'avi': 'video',
    'wmv': 'video',
    'mpg': 'video',
    'flv': 'video',
    'aac': 'audio',
    'mid': 'audio',
    'mp3': 'audio',
    'm4a': 'audio',
    'ogg': 'audio',
    'flac': 'audio',
    'wav': 'audio',
    'amr': 'audio',
    'ppt': 'slide',
    'pptm': 'slide',
    'pptx': 'slide',
    'xlsx': 'excel',
    'xlsm': 'excel',
    'xlsb': 'excel',
    'xltx': 'excel',
    'xltm': 'excel',
    'xls': 'excel',
    'xlt': 'excel',
    'xls': 'excel',
    'xlam': 'excel',
    'xla': 'excel',
    'xlw': 'excel',
    'xlr': 'excel',
    'xml': 'excel',
    'doc': 'word',
    'docm': 'word',
    'docx': 'word',
    'dot': 'word',
    'dotm': 'word',
    'dotx': 'word',
}

def detect_file_type(file_name):
    suffix = Path(file_name).suffix
    return file_types.get(suffix.strip('.'), 'undefined')