# Generated by Django 3.2.8 on 2021-10-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drive.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stared', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_set', to='drive.folder')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(default='undefined', max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_on', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('size', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_object', models.FileField(upload_to=drive.utils.file_direcotory_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='drive.folder')),
                ('shared_users', models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('stared_users', models.ManyToManyField(blank=True, related_name='stared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.file')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
