# Generated by Django 3.2.8 on 2021-10-26 16:10

from django.db import migrations, models
import drive.utils


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_object',
            field=models.FileField(blank=True, null=True, upload_to=drive.utils.file_direcotory_path),
        ),
    ]
